# Generated by Django 5.0.6 on 2024-06-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='provider',
            field=models.CharField(choices=[('Управляющая компания', 'УК "Орион"'), ('МОЭК', 'МОЭК'), ('Мосводоканал', 'Мосводоканал'), ('Мосэнергосбыт', 'Мосэнеросбыт'), ('ЕПД', 'Единый платежный документ'), ('Интернет', '108Телеком')], max_length=20, verbose_name='Поставщик услуги'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('Предоплата', 'Предоплата'), ('Текущий платеж', 'Текущий платеж'), ('Постоплата', 'Постоплата')], max_length=20, verbose_name='Тип договора'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=20, verbose_name='Период оплаты'),
        ),
    ]
