# Generated by Django 5.0.6 on 2024-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_contract_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='provider',
            field=models.CharField(choices=[('Управляющая компания', 'Управляющая компания'), ('МОЭК', 'МОЭК'), ('Мосводоканал', 'Мосводоканал'), ('Мосэнергосбыт', 'Мосэнергосбыт'), ('ЕПД', 'ЕПД'), ('Интернет', 'Интернет')], max_length=20, verbose_name='Поставщик услуги'),
        ),
    ]
